### ISSUE TITLE
front/Menú navbar

### ISSUE THREAD

**Issue by alexmarinmendez** [emanuelpps/s15-01-m-node-react-Private-#12]
Como usuario, quiero disponer de un menú de navegación para acceder a categorías, a la gestión de cuenta y, si soy creador de contenido, a la página de gestión de contenido, así como iniciar o cerrar sesión

**Comment by DMRamirezZarta** [comment]
Feedback sobre el Menú Navbar

Pruebas Automatizadas con Cypress

1. Renderizado del Navbar

- Título del Sitio:
  - El título "Indie Zone" se muestra correctamente.
- Botón de Acceder:
  - El botón "Acceder" está presente y visible.

2.  Funcionalidad del Navbar

- Enlace al Inicio:
  - El título "Indie Zone" redirige correctamente a la página de inicio.
- Enlace de Acceder:
  - El botón "Acceder" redirige correctamente a la página de login (/login).

3. Responsividad del Navbar

- El Navbar se adapta correctamente a diferentes tamaños de pantalla (escritorio, tablet, móvil).


Resultados
- Todas las pruebas pasaron exitosamente.
- No se encontraron errores en las funcionalidades del menú navbar.

![Captura de pantalla (111)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/9d0d023d-1cd8-4376-a3d7-3748fc55150d)
![Captura de pantalla (112)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/ddf97a6c-d4a6-4abb-89ca-1a2b6cf7acc9)
![Captura de pantalla (114)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/dd169b2f-ba31-40da-915d-7a4616d7b271)

[TC-12.xlsx](https://github.com/user-attachments/files/15526653/TC-12.xlsx)
@alexmarinmendez @SebasPalmaSan
