### ISSUE TITLE
front/Footer con información y navegación externa

### ISSUE THREAD

**Issue by alexmarinmendez** [emanuelpps/s15-01-m-node-react-Private-#13]

**Comment by DMRamirezZarta** [comment]
Feedback sobre Footer y Navegación Externa:

Proceso de Pruebas:
Se realizaron pruebas manuales exhaustivas en diversas páginas del sitio web, incluidas la página principal, la página de inicio de sesión, la página de registro y la página de suscripción.
Se utilizó la herramienta de extensión Responsive Viewer de Google Chrome para simular varios tamaños de pantalla y verificar la adaptabilidad del footer en dispositivos móviles.
Además, se llevó a cabo una prueba manual en un dispositivo real, un teléfono Motorola One Macro, para evaluar la experiencia del usuario en un entorno móvil.

Durante la evaluación de la adaptabilidad del footer y la funcionalidad de la navegación externa en el sitio web, se observaron los siguientes puntos:

Adaptabilidad del Footer:

Se constató que el footer se adapta de manera satisfactoria a diferentes tamaños de pantalla en las páginas del sitio web, ofreciendo una experiencia coherente para los usuarios.

Navegación Externa:
Aunque el footer contiene por ejemplo el aviso de politica de privacidad que deberían dirigir a páginas externas, se evidenció que no tienen funcionalidad.
Tras revisar el código, se encontró que el aviso de politica de privacidad esta dentro de etiquetas <span> en lugar de etiquetas <a>, lo que indica que actualmente no tienen funcionalidad.
Por lo tanto, durante las pruebas, se enfocó únicamente en verificar la parte visual del footer y no se evaluaron los enlaces, ya que estos no estaban implementados.

Conclusión:
El footer del sitio web muestra una buena adaptabilidad en la mayoría de las páginas. Respecto a la navegación externa, se identificó que el footer no tiene hipervinculos. Además, se confirma que el footer se muestra correctamente en los navegadores Mozilla Firefox y Microsoft Edge, asegurando una experiencia consistente en diferentes plataformas.

herramientas Utilizadas
1-Google Chrome (navegador)
2-Editor de Código Visual (VS Code)
3-Extensión de Google Chrome: Responsive Viewer
4-Navegadores Mozilla Firefox y Microsoft Edge
5-Microsoft Excel

[TC-13.xlsx](https://github.com/user-attachments/files/15571763/TC-13.xlsx)


@SebasPalmaSan @alexmarinmendez
