### ISSUE TITLE
front/Página de suscripción

### ISSUE THREAD

**Issue by emanuelpps** [emanuelpps/s15-01-m-node-react-Private-#18]

**Comment by DMRamirezZarta** [comment]
Feedback

1- Las pruebas de funcionalidad demostraron que el botón "Suscríbete" y la página de suscripción funcionan como se espera.
2- Se identificaron problemas de responsividad en la vista móvil, como la falta de ajuste de diseño y la visibilidad de elementos.
3- Se utilizó Cypress para realizar las pruebas automatizadas y se verificó visualmente con la extensión "Responsive Viewer" en Google Chrome, así como en un dispositivo real, un celular Motorola.
4- Se adjuntan capturas de pantalla como evidencia de los resultados obtenidos.
Observaciones: Aunque las pruebas automatizadas pasaron, se recomienda realizar un retesteo de la responsividad en una fecha posterior para garantizar una experiencia de usuario óptima en todos los dispositivos.

-capturas de pantalla dispositivo movil motorola one macro

![WhatsApp Image 2024-06-02 at 5 34 32 PM (1)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/c1ce4941-384d-4bb0-8021-df44ef3a92a3)
![WhatsApp Image 2024-06-02 at 5 34 32 PM](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/c28e4535-4432-4514-b6a5-5f7aa4cdadb4)
![WhatsApp Image 2024-06-02 at 5 34 31 PM](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/af7c7190-5c45-4b93-9cb0-bc8846f3cd84)

-capturas de pantalla extension de google

![Captura de pantalla (116)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/3dbb110d-e67d-46c8-8089-0a8b6e5fd018)
![Captura de pantalla (117)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/a9591d8e-7f39-4a03-8689-35da7ab92d8b)
![Captura de pantalla (118)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/6f5cb26b-b8f3-4e9d-8f30-1f48ca81298f)

-capturas de pantallas de pruebas en cypress

![Captura de pantalla (120)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/7fc3dc70-56e9-4286-87f2-7928e76651c5)
![Captura de pantalla (123)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/40194c08-b15d-41d0-91f6-fe54bc4dfb3e)

[TC-18.xlsx](https://github.com/user-attachments/files/15527125/TC-18.xlsx)
@alexmarinmendez @emanuelpps
