### ISSUE TITLE
front/Inicio de sesión de usuario

### ISSUE THREAD

**Issue by alexmarinmendez** [emanuelpps/s15-01-m-node-react-Private-#2]
Como usuario quiero poder iniciar sesión en mi cuenta para acceder a contenido exclusivo y personalizado

**Comment by DMRamirezZarta** [comment]
Feedback
1-Verificación de Redirección
-Botón de Acceder:
El botón "Acceder" redirige correctamente a la página de login (/login).
2-Enlace de Registrate:
-El enlace "Registrate" redirige correctamente a la página de registro (/register).
3.Carga Correcta de Páginas
-Página de Login:
  -El formulario de login se muestra correctamente y es visible.
-Página de Registro:
  -El formulario de registro se muestra correctamente y es visible.
4-Responsividad de Páginas
 -Página de Login
  -El formulario de login se adapta correctamente.
 -Página de Registro
  -El formulario de registro se adapta correctamente.

Herramientas Utilizadas
-Cypress: Para la automatización de pruebas end-to-end.
-Motorola One Macro: Para pruebas manuales en un dispositivo móvil físico.
-Responsive Viewer (extensión de Google Chrome): Para la simulación de diferentes tamaños de pantalla y pruebas de 
 responsividad.
- Excel para informe 


Resultados
-Todas las pruebas automatizadas pasaron exitosamente.
-Las pruebas manuales revelaron problemas de adaptación del sombreado detrás del formulario en algunas pantallas.

Observaciones
-Se presenta el feedback de los dos casos de prueba (login y register) conjuntamente porque ambos están relacionados con el 
 flujo o recorrido del usuario en la página.
-Las pruebas manuales realizadas en un teléfono Motorola One Macro y con la extensión "Responsive Viewer" de Google 
 mostraron que en algunas pantallas, el sombreado detrás del formulario no se adapta correctamente. se adjuntan capturas de 
 pantalla como evidencia.

Sugerencias
-Revisar y corregir los problemas de responsividad del sombreado detrás del formulario en las páginas de login y registro, 
 especialmente en dispositivos móviles.
-Realizar pruebas de validación después de las correcciones para asegurar que los problemas de adaptación hayan sido 
 solucionados.

Capturas de pantalla de telefono motorola one macro

![WhatsApp Image 2024-06-02 at 7 02 50 PM (1)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/a9d25e35-2ea3-4c02-aa52-4db7fea4ec77)
![WhatsApp Image 2024-06-02 at 7 02 50 PM (2)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/2ddfd573-5314-4ea2-96e5-0ab00731d15b)
![WhatsApp Image 2024-06-02 at 7 02 50 PM (3)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/82e8ae8f-fab5-4432-b25f-346fb1d1ec12)
![WhatsApp Image 2024-06-02 at 7 02 50 PM](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/07d52737-23f5-471c-b2e9-75c5e27c8985)

capturas de pantalla Responsive Viewer

![Captura de pantalla (128)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/adf8abd4-c4b2-43a7-9fc2-5b2ccfae4ca7)

capturas de pantalla cypress

![Captura de pantalla (129)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/a9d970e1-e7ec-4c00-962d-70f62feeca6e)
![Captura de pantalla (132)](https://github.com/emanuelpps/s15-01-m-node-react-Private-/assets/136834008/5ea863e1-7c8b-4a15-8e07-26f21c986417)

Informe excel

[TC-01-TC-02.xlsx](https://github.com/user-attachments/files/15528331/TC-01-TC-02.xlsx)


@alexmarinmendez @emanuelpps
